
print('* * * * *')
print('* * * * *')
print('* * * * *')
print('\n')
print('* * * * *')
print('*       *')
print('* * * * *')
print('\n')
print('  * *')
print('*     *')
print('*     *')
print('*     *')
print('  * *')
print('\n')
print('* * * * *')
print('  * * * ')
print('  * * * ')
print('  * * * ')
print('* * * * *')

print('QUE HUONG')
print('* * *')
print('Que huong la chum khe ngot')
print('\tCho con treo hai moi ngay')
print('\t\tQue huong la duong di hoc')
print('\t\t\tCon ve rop buom vang bay')
print('* * *')
print('\t\t\t\t\tDo Trung Quan')